hooks:
  BeforeInstall:
    - location: scripts/clean_old.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/fix_permissions.sh    # chowns back to ubuntu
      timeout: 300
      runas: root

    - location: scripts/deploy.sh             # your backend steps
      timeout: 300
      runas: ubuntu

    - location: scripts/build_frontend.sh     # will now npm ci & build cleanly
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/restart_nginx.sh
      timeout: 60
      runas: root
