version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/QuizMaster

hooks:
  BeforeInstall:
    - location: scripts/clean_old.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu

    - location: scripts/build_frontend.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/restart_nginx.sh
      timeout: 60
      runas: root
